version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/packages/at-seo'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/packages/gatsby-plugin-blogcore'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/packages/gatsby-plugin-sitemap'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/packages/csp'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/packages/i18n-utils'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/packages/slugify'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/packages/traslit'
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: '/packages/utils'
    schedule:
      interval: monthly
