name: Auto Merge
on:
  pull_request:
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
